# Generated by Django 3.2.7 on 2021-11-19 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('submission_date', models.DateTimeField()),
                ('upload_file', models.FileField(upload_to='uploads/')),
                ('is_plagiarised', models.BooleanField(default=0)),
                ('is_submitted', models.BooleanField(default=0)),
                ('is_accepted', models.BooleanField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.studentprofile')),
            ],
        ),
    ]
