# Generated by Django 3.2.7 on 2021-11-21 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_alter_notice_post_date'),
        ('clsses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='issue_date',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.notice_post'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 42, 2, 286240)),
        ),
    ]
