# Generated by Django 3.2.7 on 2021-11-21 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsses', '0002_auto_20211121_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 14, 48, 9, 728661)),
        ),
    ]
