# Generated by Django 3.2.7 on 2021-11-24 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsses', '0003_alter_assignment_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 14, 28, 20, 606214)),
        ),
    ]
