# Generated by Django 3.2.7 on 2021-11-26 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsses', '0008_alter_assignment_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 20, 18, 59, 577534)),
        ),
    ]
