# Generated by Django 3.2.7 on 2021-11-29 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0013_auto_20211126_2019'),
        ('clsses', '0009_alter_assignment_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.assignment_post'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 22, 44, 14, 717138)),
        ),
    ]
