# Generated by Django 3.2.7 on 2021-11-29 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsses', '0010_auto_20211129_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='subject_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 22, 49, 10, 651037)),
        ),
    ]
