# Generated by Django 3.2.7 on 2021-11-29 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsses', '0011_auto_20211129_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 22, 55, 7, 866433)),
        ),
    ]
