# Generated by Django 3.2.7 on 2021-11-29 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsses', '0013_alter_assignment_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_submitted',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
