# Generated by Django 3.2.7 on 2021-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsses', '0014_auto_20211129_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
