# Generated by Django 3.2.7 on 2021-11-20 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_post_is_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_post',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notice_post',
            name='subject',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notice_post',
            name='template_docx',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 1, 57, 31, 711219)),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='image_content',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
