# Generated by Django 3.2.7 on 2021-11-20 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20211121_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_post',
            name='desig',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 2, 4, 10, 67607)),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='template_docx',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name=''),
        ),
    ]
