# Generated by Django 3.2.7 on 2021-11-20 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0004_auto_20211121_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 2, 26, 7, 8485)),
        ),
    ]
