# Generated by Django 3.2.7 on 2021-11-21 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20211121_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 42, 2, 268306)),
        ),
    ]
