# Generated by Django 3.2.7 on 2021-11-24 08:58

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0007_alter_notice_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 14, 28, 20, 592177)),
        ),
        migrations.CreateModel(
            name='Assignment_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, null=True)),
                ('desig', models.CharField(max_length=50, null=True)),
                ('subject', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15, null=True), blank=True, null=True, size=None)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 24, 14, 28, 20, 593212))),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(max_length=300)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('template_docx', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
