# Generated by Django 3.2.7 on 2021-11-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20211124_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_post',
            name='date',
            field=models.DateTimeField(default='24/11/21'),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default='24/11/21'),
        ),
    ]
