# Generated by Django 3.2.7 on 2021-11-24 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_auto_20211124_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_post',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 24)),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 24)),
        ),
    ]
