# Generated by Django 3.2.7 on 2021-11-25 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0011_auto_20211124_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notice_post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 18, 51, 11, 237166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 18, 51, 11, 236165, tzinfo=utc)),
        ),
    ]
