# Generated by Django 3.2.7 on 2021-11-26 14:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0012_auto_20211126_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment_post',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
